 "Month Name", each Date.ToText(Date.From([FECHA_Y_HORA_ABIERTO]),"dd-MMM"), type text),
  Table.AddColumn(#"Inserted Month Name", "Length", each Text.Length([Month Name]), Int64.Type),
Time.Hour([FECHA_Y_HORA_ABIERTO]) < 6 then "00AM-05AM "
Date.Month([FECHA_Y_HORA_ABIERTO]) = Date.Month(DateTime.LocalNow())-1
